### ISSUE TITLE
shot sounds missing

### ISSUE THREAD

**Issue by napo1emon** [andtheherois/3DS-ISG-AK-Makeover#1]
https://discord.com/channels/912320241713958912/1219433143069708299/1304562804736528414

After some deliberation Oleh said that the issue is due to bad configs. Something about missing parent section inheritance in the first line of LTX files. I don't get it but after adding the parts with `wpn_ak**_sounds` the sounds are playing fine:

w_ak74_isg.ltx `[wpn_ak74_isg]:identity_immunities,weapon_probability,default_weapon_params,wpn_ak74_sounds`
w_akm_isg.ltx `[wpn_akm_isg]:identity_immunities,weapon_probability,default_weapon_params,wpn_akm_sounds`
w_aksu_isg.ltx `[wpn_ak74u_isg]:identity_immunities,weapon_probability,default_weapon_params,wpn_ak12_sounds`

Interestingly, the w_aksu_m1_isg is also missing the `wpn_ak**_sounds` part in the config, but the sound issue is not present here.

**Comment by andtheherois** [comment]
fixed
